package com.SCOCS.SwapToys;

/*
this code is generated by Muhammad Mazhar
date:25 dec 2018
 */
import java.util.List;

public class ToysCategory {
    public String id;
    public String Name;


    public ToysCategory(String id, String name) {
        this.id = id;
        this.Name = name;

    }
    public ToysCategory getToysCategories(){

        return new ToysCategory(this.id,this.Name);
    }
    public List<ToysCategory> getAllToysCategories(){


        };
    }

}
