package com.SCOCS.SwapToys;
/*
this code is generated by Muhammad Mazhar
date:25 dec 2018
 */


public class Toys {
    public String id;
    public String Name;
    public boolean  Status; // if status == true then toy is new otherwise used

    public  ToysCategory category;

    public Toys(String id, String userName, boolean Status, ToysCategory category) {
        this.id = id;
        this.Name = userName;
        this.Status = Status;
        this.category = category;
    }

}
